function getIrregularWordsData() {
  return [
    ['be', 'was were', 'been', 'van', 'biti', 'beginner'],
    ['become', 'became', 'become', 'válik valamivé', 'serbian', 'beginner'],
    ['break', 'broke', 'broken', 'eltör', 'serbian', 'beginner'],
    ['build', 'built', 'built', 'épít', 'serbian', 'beginner'],
    ['buy', 'bought', 'bought', 'vásárol', 'serbian', 'beginner'],
    ['begin', 'began', 'begun', 'elkezd', 'početi', 'beginner'],
    ['bring', 'brought', 'brought', 'hoz', 'donosi', 'beginner'],
    ['do', 'did', 'done', 'csinál', 'serbian', 'beginner'],
    ['can', 'could', '', 'képes', 'serbian', 'beginner'],
    ['catch', 'caught', 'caught', 'elkap', 'serbian', 'beginner'],
    ['choose', 'chose', 'chosen', 'választ', 'serbian', 'beginner'],
    ['come', 'came', 'come', 'jön', 'serbian', 'beginner'],
    ['cost', 'cost', 'cost', 'kerül valamibe', 'serbian', 'beginner'],
    ['cut', 'cut', 'cut', 'vág', 'seče', 'beginner'],
    ['draw', 'drew', 'drawn', 'rajzol', 'serbian', 'beginner'],
    ['dream', 'dreamt', 'dreamt', 'álmodik', 'serbian', 'beginner'],
    ['drink', 'drank', 'drunk', 'iszik', 'serbian', 'beginner'],
    ['drive', 'drove', 'driven', 'vezet', 'serbian', 'beginner'],
    ['eat', 'ate', 'eaten', 'eszik', 'serbian', 'beginner'],
    ['fall', 'fell', 'fallen', 'esik', 'serbian', 'beginner'],
    ['feel', 'felt', 'felt', 'érez', 'serbian', 'beginner'],
    ['find', 'found', 'found', 'talál', 'serbian', 'beginner'],
    ['fly', 'flew', 'flown', 'repül', 'serbian', 'beginner'],
    ['forget', 'forgot', 'forgotten', 'elfelejt', 'serbian', 'beginner'],
    ['get', 'got', 'got', 'kap', 'serbian', 'beginner'],
    ['give', 'gave', 'given', 'ad', 'serbian', 'beginner'],
    ['go', 'went', 'gone', 'megy', 'serbian', 'beginner'],
    ['have', 'had', 'had', 'birtokol', 'serbian', 'beginner'],
    ['hear', 'heard', 'heard', 'hall', 'serbian', 'beginner'],
    ['hide', 'hid', 'hidden', 'elrejt', 'serbian', 'beginner'],
    ['hit', 'hit', 'hit', 'üt', 'serbian', 'beginner'],
    ['hurt', 'hurt', 'hurt', 'megsért', 'serbian', 'beginner'],
    ['keep', 'kept', 'kept', 'tart', 'serbian', 'beginner'],
    ['know', 'knew', 'known', 'tud', 'serbian', 'beginner'],
    ['learn', 'learnt', 'learnt', 'megtanul', 'serbian', 'beginner'],
    ['leave', 'left', 'left', 'elhagy', 'serbian', 'beginner'],
    ['lose', 'lost', 'lost', 'elveszít', 'serbian', 'beginner'],
    ['make', 'made', 'made', 'készít', 'serbian', 'beginner'],
    ['meet', 'met', 'met', 'találkozik', 'serbian', 'beginner'],
    ['pay', 'paid', 'paid', 'fizet', 'serbian', 'beginner'],
    ['put', 'put', 'put', 'tesz', 'stavlja', 'beginner'],
    ['read', 'read', 'read', 'olvas', 'cita', 'beginner'],
    ['ride', 'rode', 'ridden', 'lovagol', 'jase', 'beginner'],
    ['run', 'ran', 'run', 'fut', 'trci', 'beginner'],
    ['say', 'said', 'said', 'mond', 'kaze', 'beginner'],
    ['see', 'saw', 'seen', 'lát', 'vidi', 'beginner'],
    ['sell', 'sold', 'sold', 'elad', 'prodaje', 'beginner'],
    ['send', 'sent', 'sent', 'elküld', 'salje', 'beginner'],
    ['sing', 'sang', 'sung', 'énekel', 'peva', 'beginner'],
    ['sit', 'sat', 'sat', 'leül', 'sedi', 'beginner'],
    ['sleep', 'slept', 'slept', 'alszik', 'sedi', 'beginner'],
    ['speak', 'spoke', 'spoken', 'beszél', 'prica', 'beginner'],
    ['spend', 'spent', 'spent', 'költ tölt', 'tros', 'beginner'],
    ['stand', 'stood', 'stood', 'áll', 'stoji', 'beginner'],
    ['steal', 'stole', 'stolen', 'lop', 'krade', 'beginner'],
    ['swim', 'swam', 'swum', 'úszik', 'pliva', 'beginner'],
    ['take', 'took', 'taken', 'visz rak tesz', 'uzima', 'beginner'],
    ['tell', 'told', 'told', 'mond', 'kaze', 'beginner'],
    ['think', 'thought', 'thought', 'gondol', 'misli', 'beginner'],
    ['understand', 'understood', 'understood', 'megért', 'razume', 'beginner'],
    ['wake', 'woke', 'woken', 'ébred', 'budi', 'beginner'],
    ['wear', 'wore', 'worn', 'visel', 'nosi', 'beginner'],
    ['win', 'won', 'won', 'győz', 'pobeduje', 'beginner'],
    ['write', 'wrote', 'written', 'ír', 'pise', 'beginner']
  ];
}