function getPresentContinueSentences() {
    return [
      ["I ___ at the moment.", 'work', 'am working', "'m working"],
      ["I ___ at the moment.", 'not work', 'am not working', "'m not working"],
      ["__ I ___ at the moment?", 'work', 'am working'],
      ["I ___ at the moment.", 'read', 'am reading', "'m reading"],
      ["I'm musician. What  ___ ?", 'you do', 'do you do'],
      ["I'm doctor. What  ___ ?", 'you do', 'do you do'],
      ["I'm nurse. What  ___ ?", 'you do', 'do you do'],
      ["I'm teacher. What  ___ ?", 'you do', 'do you do'],
      ["I can't go out. I ___ my homework.", 'do', 'am doing', "'m doing"],
      ["I can go out. I ___ my homework.", 'not do', 'am not doing', "'m not doing"],
      ["Sandra ____ jeans today.", 'not wear', 'is not wearing', "isn't wearing"],
      ["__ your cousin ____ with you these days?", 'live', 'is living'],
      ["___ they ____ at the moment?", 'work', 'are working'],
      ["The sun ____ today.", 'shine', 'is shining'],
      ["Jack ____ the piano at the moment.", 'play', 'is playing', "'s playing"],
      ["I ____ now. Goodbye!", 'go', 'am going', "'m going"],
      ["It ____ . Can I take their umbrella?", 'rain', 'is raining', "'s raining"],
      ["I ___ an article about animals at the moment.", "write", "am writing", "'m writing"],
      ["He ___ a book, right now.", "read", "is reading"], 
      ["They ___ football now.", "play", "are playing"],
      ["She ___ a coffee, right now.", "drink", "is drinking"],
      ["He ___ to the library, right now.", "go", "is going"],
      ["We ___ for shopping in this market right now.", "come", "are coming"],
      ["We ___ a movie in this Cineplex right now.", "watch", "are watching"],
      ["You ___ in that market at the moment", "shop", "are shopping"],
      ["I ___ at church today.", 'sing', "am singing", "'m singing"],
      ["I ___ at church today.", 'not sing', "am not singing", "'m not singing"],
      ["___ I ___ at church today?", 'sing', "am singing"],
      ["The boys ___ ball after school.", "play", "are playing"],
      ["Right now, She ___.", "cry", "is crying"],
      ["Now, he ___ to his friend.", "talk", "is talking"],
      ["Right now, the baby ___ in his crib.", "sleep", "is sleeping"],
      ["We ___ the museum in the afternoon.", "visit", "are visiting"],
      ["He ___ at the moment.", "not stand", "is not standing"],
      ["Anthony ___ in the chair, right now.", "seat", "is sitting"],
      ["You ___ the movie, right now.", "not watch", "are not watching"],
      ["Rose ___ a book, right now.", "read", "is reading"],
      ["Rose ___ a book, right now.", "not read", "is not reading", "isn't reading"]
    ];
  }