function getPresentSimpleSentences() {
    return [
      ["My brother ___ in a bank.", "work", "works"],
      ["My brother ___ in a bank.", "not work", "does not work", "doesn't work"],
      ["___ my brother ___ in a bank?", "work", "does work"],
      ["Her parents ___ in Scotland.", "live", "live"],
      ["Her parents ___ in Scotland.", "not live", "do not live", "don't live"],
      ["Where ___ Her parents ___ ?", "live", "do live"],
      ["John ___ shower every day.", "have", "has"],
      ["John ___ shower every day.", "not have", "does not have", "doesn't have"],
      ["___ John ___ shower every day?", "have", "does have"],
      ["I ___ football.", "like", "like"],
      ["I ___ football.", "not like", "do not like", "don't like"],
      ["__ I ___ football?", "like", "do like"],
      ["My car ___ lot of petrol.", "use", "uses"],
      ["My car ___ lot of petrol.", "not use", "does not use", "doesn't use"],
      ["___ My car ___ lot of petrol?", "use", "does use"],
      ["Sandra ____ Spanish.", "speak", "speaks"],
      ["Sandra ____ Spanish.", "not speak", "does not speak", "doesn't speak"],
      ["___ Sandra ____ Spanish?", "speak", "does speak"],
      ["He ___ english every day.", "study", "studies"],
      ["He ___ english every day.", "not study", "does not study", "doesn't study"],
      ["___ he ___ english every day?", "not study", "does study"],
      ["He ___ at church every Sunday.", 'sing', "sings"],
      ["He ___ at church every Sunday.", 'not sing', "does not sing", "doesn't sing"],
      ["Where ___ He ___ at every Sunday?", 'sing', "does sing"],
      ["They ___ football every Sunday.", "play", "play"],
      ["They ___ football every Sunday.", "not play", "do not play", "don't play"],
      ["What kind of game ___ they ___ every Sunday?", "play", "do play"],
      ["On witch day ___ they ___ football?", "do play", "do play"],
      ['My dad usually ___ to work.', 'drive', 'drives'],
      ['My dad usually ___ to work.', 'not drive', 'does not drive', "doesn't drive"],
      ['When ___ my dad ___ to work?', 'drive', 'does drive'],
      ['Their plane ___ at 9 am.', 'leave', 'leaves'],
      ['We  ___ meat every day.', 'not eat', 'do not eat', "don't eat"],
      ['I never ___ this computer.', 'use', 'use'],
      ['She ___ coffee.', 'not drink', 'does not drink', "doesn't drink"],
      ['She ___ coffee.', 'drink', 'drinks'],
      ['___ she ___ coffee?', 'do drink', 'does drink'],
      ["Sandra usually ____ jeans.", 'not wear', 'does not wear', "doesn't wear"],
      ["Sandra usually ____ jeans.", 'wear', 'wears'],
      ["What kind of clothes ____ Sandra usually ____ ?", 'wear', 'does wear'],
      ["We ____ cake for breakfast every day.", 'have', 'have'],
      ["We ____ cake for breakfast every day.", 'not have', 'do not have', "don't have"],
      ["___ We ____ cake for breakfast every day?", 'do have', 'do have'],
      ["___ she ___ her grandparents every week?", 'do visit', 'does visit'],
      ["She ____ her grandparents every week.", 'visit', 'visits'],
      ["She ____ her grandparents every week.", 'not visit', 'does not visit', "doesn't visit"],
      ["I ____ to this radio show every week", 'listen', 'listen'],
      ["I ____ to this radio show every week", 'not listen', 'do not listen', "don't listen"],
      ["___ I ____ to this radio show every week?", 'do listen', 'do listen'],
      ["Children usually ____ chocolate.", 'like', 'like'],
      ["Julia allways ____ parties.", 'enjoy', 'enjoys'],
      ["Jack ____ the piano very well.", 'play', 'plays'],
      ["I ____ TV very much!", 'not watch', "do not watch","don't watch"],
      ["I ___ tennis.", "play", "play"],
      ["I ___ tennis.", "not play", "do not play", "don't play"],
      ["__ I ___ tennis?", "do play", "do play"],
      ["She ____ tennis.", "play", "plays"],  
      ["She ____ tennis.", "not play", "does not play", "doesn't play"],
      ["When ___ she ____ tennis?", "play", "does play"],
      ["Where ___ she ____ tennis.", "play", "does play"],    
      ["The train ___ every morning at 8 AM.", "leave", "leaves"],
      ["The train ___ at 9 AM.", "not leave", "does not leave", "doesn't leave"],
      ["When ___ the metro usually ___?", "leave", "does leave"],
      ["When ___ the train usually ___?", "leave", "does leave"],
      ["When ___ the airplane usually ___?", "leave", "does leave"],
      ["She always ___ her purse.", "forget", "forgets"],
      ["She never ___ her purse.", "forget", "forgets"],
      ["She usually ___ her purse.", "forget", "forgets"],
      ["He never ____ his wallet.", "forget", "forgets"],
      ["I come from Canda. Where __ you __ from?", "come", "do come"],
      ["I ___ up at 8 o'clock every morning.","get","get"],
      ["My mother ___ up at 8 o'clock every morning.","get","gets"],
      ["My mother ___ up at 8 o'clock every morning.","not get","does not get","doesn't get"],
      ["When ___ your mother ___ up every morning?","get","does get"],
      ["Rice ___ in warm climates.","grow","groves"],
      ["Rice ___ in warm climates.","not grow","does not grow","doesn't grow"],
      ["In what climates ___ rice ___ ?","grow","does grow"],
      ["Water ___ at 100 degrees celsius.","boil","boils"],
      ["Water ___ at 10 degrees celsius.","not boil","does not boil", "doesn't boil"],
      ["At what temperature ___ water ___ ?","boil","does boil"]
    ];
  }