function getTimePrepositionsSentences() {
  return [
    [
      'There were many inventions __ the twentieth century.',
      'in at for on',
      'in'
    ],
    ['She left school __ 1987.', 'in at for on', 'in'],
    ['He’s leaving __ January.', 'in at for on', 'in'],
    ['We usually go __ holiday __ summer.', 'in at for on', 'on in'],
    [
      'I’m leaving __ the morning, not __ the evening.',
      'in at for on',
      'in in'
    ],
    ['It rained __ the night.', 'in at for on', 'in', 'during'],
    ['She played tennis __ an hour.', 'in at for on', 'for'],
    ['I play tennis __ the weekend.', 'in at for on', 'at'],
    ['I go to sleep __ night.', 'in at for on', 'at'],
    [
      'The appointment is __ four o’clock __ the afternoon.',
      'in at for on',
      'at in'
    ],
    ['The appointment is __ Monday.', 'in at for on', 'on'],
    ['I’m leaving __ 12 December.', 'in at for on', 'on'],
    ["I start work __ 8'clock.", 'in at for on', 'at'],
    ['The shop close __ 5.30.', 'in at for on', 'at'],
    ['Goodbye! See you __ Friday.', 'in at for on', 'on'],
    ['I dont works __ Sundays.', 'in at for on', 'on'],
    ['The concert is __ 22 December.', 'in at for on', 'on'],
    ['I’m going on holiday __ October.', 'in at for on', 'in'],
    ['Emma left school __ 2010.', 'in at for on', 'in'],
    ['The garden is lovely __ spring .', 'in at for on', 'in'],
    ['Are you going away __ the weekend?', 'in at for on', 'at'],
    ["I can't sleep __ night.", 'in at for on', 'at'],
    ['Where would you be __ Christmas?', 'in at for on', 'at'],
    ['Where would you be __ Christmas day?', 'in at for on', 'on'],
    ["I'm going on holiday __ the end of October.", 'in at for on', 'at'],
    ['Are you busy __ the moment?', 'in at for on', 'at'],
    ['I allways feel good __ the morning.', 'in at for on', 'in'],
    ['Do you often go out __ the evening?', 'in at for on', 'in'],
    ['I meeting Jill __ Monday morning.', 'in at for on', 'on'],
    ['Are you doing anything __ Saturday evening?', 'in at for on', 'at'],
    ['__ 6 June.', 'in at for on', 'on'],
    ['__ the evening.', 'in at for on', 'in'],
    ['__ half past two.', 'in at for on', 'at'],
    ['__ Wednesday.', 'in at for on', 'on'],
    ['__ 2017.', 'in at for on', 'in'],
    ['__ September.', 'in at for on', 'in'],
    ['__ 24 September.', 'in at for on', 'on'],
    ['__ Thursday.', 'in at for on', 'on'],
    ['__ 11.45.', 'in at for on', 'at'],
    ['__ Christmas Day.', 'in at for on', 'on'],
    ['__ Christmas.', 'in at for on', 'at'],
    ['__ the morning.', 'in at for on', 'in'],
    ['__ Friday morning.', 'in at for on', 'on'],
    ['__ Saturday night.', 'in at for on', 'on'],
    ['__ night.', 'in at for on', 'at'],
    ['__ the end of the day.', 'in at for on', 'at'],
    ['__ the weekend.', 'in at for on', 'at'],
    ['__ winter.', 'in at for on', 'in']
  ];
}
