function getMojTvojData() {
  return [
    ['Ta sveska je ____ .', 'moja', 'been', 'ženski rod', 'biti', 'beginner'],
    ['Ta torba je ____ .', 'moja', 'been', 'ženski rod', 'biti', 'beginner'],
    ['Ta riba je ____ .', 'moja', 'been', 'ženski rod', 'biti', 'beginner'],
    ['Ta kuća je ____ .', 'moja', 'been', 'ženski rod', 'biti', 'beginner'],
    ['Ta pernica je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta olovka je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta soba je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta gumica je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta suknja je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta košulja je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta jakna je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta trenerka je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta haljina je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta majica je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta devojčica je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta viljuška je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Ta kašika je ____ .', 'moja', 'become', 'ženski rod', 'serbian', 'beginner'],
    ['Taj krevet je ___ .', 'moj', 'broken', 'muški rod', 'serbian', 'beginner'],
    ['Taj nož je ___ .', 'moj', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Taj ormar je ___ .', 'moj', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Taj kauč je ___ .', 'moj', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Taj duks je ___ .', 'moj', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Taj džemper je ___ .', 'moj', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Taj telefon je ___ .', 'moj', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Taj kompjuter je ___ .', 'moj', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Taj dečak je ___ .', 'moj', 'broken', 'muški rod', 'serbian', 'beginner'],
    ['Taj auto je ___ .', 'moj', 'broken', 'muški rod', 'serbian', 'beginner'],
    ['Taj avion je ___ .', 'moj', 'broken', 'muški rod', 'serbian', 'beginner'],
    ['Taj voz je ___ .', 'moj', 'broken', 'muški rod', 'serbian', 'beginner'],
    ['Te papuče su ___ .', 'moje', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Te čarape su ___ .', 'moje', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Te patike su ___ .', 'moje', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Te čizme su ___ .', 'moje', 'built', 'muški rod', 'serbian', 'beginner'],
    ['Te pantalone su ___ .', 'moje', 'built', 'muški rod', 'serbian', 'beginner'],
    ['To zvono je ___.', 'moje', 'bought', 'srednji rod', 'serbian', 'beginner'],
    ['To mače je ___.', 'moje', 'bought', 'srednji rod', 'serbian', 'beginner'],
    ['To štene je ___.', 'moje', 'bought', 'srednji rod', 'serbian', 'beginner'],
    ['To biciklo je ___.', 'moje', 'bought', 'srednji rod', 'serbian', 'beginner'],
    
  ];
}